default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: open_flights_development

test:
  <<: *default
  database: open_flights_test

production:
  <<: *default
  database: open_flights_production
  username: open_flights
  password: <%= ENV["OPEN_FLIGHTS_DATABASE_PASSWORD"] %>
