default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DATABASE_USER')     { postgres } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { postgres } %>
  host:     <%= ENV.fetch('DATABASE_HOST')     { localhost } %>
  port:     <%= ENV.fetch('DATABASE_PORT')     { 5432 } %>
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { open_flights_development } %>

test:
  <<: *default
  database: open_flights_test

production:
  <<: *default
  database: open_flights_production
  username: open_flights
  password: <%= ENV["OPEN_FLIGHTS_DATABASE_PASSWORD"] %>
